/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContactMe: typeof import('./src/components/section/ContactMe.vue')['default']
    CurveComponent: typeof import('./src/components/navigation/nav/curve/CurveComponent.vue')['default']
    FooterComponent: typeof import('./src/components/navigation/nav/footer/FooterComponent.vue')['default']
    FooterSection: typeof import('./src/components/section/FooterSection.vue')['default']
    JumbotronSection: typeof import('./src/components/section/JumbotronSection.vue')['default']
    LinkAnimationComponent: typeof import('./src/components/navigation/LinkAnimationComponent.vue')['default']
    LinkComponent: typeof import('./src/components/navigation/nav/link/LinkComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/navigation/NavbarComponent.vue')['default']
    NavbarFloatingActionButton: typeof import('./src/components/utils/NavbarFloatingActionButton.vue')['default']
    NavComponents: typeof import('./src/components/navigation/NavComponents.vue')['default']
    ProfileSection: typeof import('./src/components/section/ProfileSection.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServicesSection: typeof import('./src/components/section/ServicesSection.vue')['default']
  }
}
